### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by anastasiaKretova** [anton-bannykh/intro17#101]
Дайте алгоритм для 2 задания, пожалуйста.

**Comment by anton-bannykh** [comment]
На вход int[], на выход int
Сумма числа нулей в конце двоичного представления числа
{10, 8} -> 4
P.S. Можно воспользоваться [Integer.numberOfTrailingZeros](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#numberOfTrailingZeros(int))
