### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by Mervap** [anton-bannykh/intro17#104]
Хочу 5 задание

**Comment by anton-bannykh** [comment]
Надо сделать так, чтобы код обработки строк в массив и код обработки массива зависили на код с main, а не наоборот. Для этого скорее можно рядом с main определить 2 интерфейса и @Inject'ить их.

**Comment by anton-bannykh** [comment]
Извини, что долго не отвечал. Впредь если не отвечаю пару дней - пинай в телеграме

**Comment by anton-bannykh** [comment]
Понятно примерно?

**Comment by Mervap** [comment]
Пока не очень, но я почитаю про все это и что не понятно спрошу в телеграмме
