### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by Mervap** [anton-bannykh/intro17#36]
Прошу выделить мне алгоритм для 2 задания

**Comment by anton-bannykh** [comment]
На вход массив int[]. Вычислить медиану.
P.S. Массив можно модифицировать. Можно воспользоваться [`Arrays.sort`](https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#sort(int[]))

**Comment by Mervap** [comment]
Медиана имеется ввиду как средний элемент в массиве, или как среднее значение всех элементов. Если первое то что делать, есть массив четной длины?

**Comment by anton-bannykh** [comment]
https://en.wikipedia.org/wiki/Median

**Comment by anton-bannykh** [comment]
{1, 2, 3} -> 2
{1, 2, 3, 4} -> 2.5

**Comment by Mervap** [comment]
Понятно, спасибо
И если массив пустой ноль выводить? Или как ошибку обрабатывать?

**Comment by anton-bannykh** [comment]
Берется среднее между двумя ближайшими к центру в отсортированном массиве

**Comment by anton-bannykh** [comment]
Давай ноль

**Comment by Mervap** [comment]
Хорошо

**Comment by anton-bannykh** [comment]
:+1:

**Comment by Mervap** [comment]
А как мне через assert'ы реализовать сравнивание даблов? Там же надо погрешности еще учитывать
