### ISSUE TITLE
Получение алгоритма(#2)

### ISSUE THREAD

**Issue by merak1t** [anton-bannykh/intro17#49]
Извините,
Я еще не сделал pull request в ветку, можете ли вы дать задание, чтобы не терять времени?

**Comment by anton-bannykh** [comment]
Сумма k-x чисел фибоначчи. На вход int[] на выход int
{0} -> 1
{1} -> 1
{1, 3} -> 4

**Comment by anton-bannykh** [comment]
Если число отрицательное или больше 15-ти, игнорировать
