### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by Roket132** [anton-bannykh/intro17#65]
I'm ready to do 2 tasks

**Comment by anton-bannykh** [comment]
на вход массив целых чисел int[]
на выход сумма степеней 5
{1, 2} -> 30
Если на вход число больше 10 - игнорировать

**Comment by Roket132** [comment]
Все числа на входе >=0 или же на выходе должен быть double?

**Comment by anton-bannykh** [comment]
Все числа >= 0

**Comment by anton-bannykh** [comment]
Точнее если < 0, то игнорировать.
Ну то есть цель в том, чтобы написать простую программу по мотивам того, что я написал. Если она в каких-то случаях не работает - это нормально, надо только на это тест написать
